<a href="https://colab.research.google.com/github/HemanthS3149/zoho_intern_work/blob/Week-4/ML_Parts_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vector,Matrix,Tensor**

Vector: 1d array of numbers used to rep data points or feature sets in ML

Matrix: A two-dimensional array of numbers. Matrices are used to represent datasets, where each row is a data point and each column is a feature.

Tensor:An nd array of numbers.Tensors generalize vectors and matrices to higher dimensions and are used in dl

In [2]:
import numpy as np
vector=np.array([1,2,3])
print(vector,"\n")

matrix=np.array([[1,2,3,],[4,5,6]])
print(matrix,"\n")

tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Gradient Descent**: is an optimization algo used to minimize loss function by iteratively moving towards minimum val of the function. It updates weights and biases by calc the gradient of loss function with resp to other parameters and adjusting them in the oposite direction of the gradient.

**Numpy, Torch, TorchVision**

Numpy: a funda library for scientific computing in Python.Provides support for large multi-dimensional arrays and matrices along with colletion of math functions to operate on these arrays

In [3]:
import numpy as np
array=np.array([1,2,3])
print(array+1)
print(array*10)

[2 3 4]
[10 20 30]


**Torch**:Core library of PyTorch, an open-source ML library for python. It provides tensor computation with strong GPU acceleration and dl capabilities.

In [4]:
import torch
tensor=torch.tensor([1,2,3])
print(tensor+1)
print(tensor*10)

tensor([2, 3, 4])
tensor([10, 20, 30])


**TorchVision:**A library that provides tools for CV,including popular datasets,model architectures and image transformations

In [5]:
from torchvision import datasets,transforms
transform=transforms.Compose([transforms.ToTensor()])#transforms can perform ops on image data like converting them to tensors in this case
mnist_dataset=datasets.MNIST(root='mnist_data',train=True,transform=transform,download=True)
#transform=transform applies the specified transformations to the images
#transforms.Compose allows you to chain multiple transformations together

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:01<00:00, 5066778.11it/s]


Extracting mnist_data/MNIST/raw/train-images-idx3-ubyte.gz to mnist_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 134354.12it/s]


Extracting mnist_data/MNIST/raw/train-labels-idx1-ubyte.gz to mnist_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:01<00:00, 1246475.78it/s]


Extracting mnist_data/MNIST/raw/t10k-images-idx3-ubyte.gz to mnist_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 8463140.28it/s]

Extracting mnist_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to mnist_data/MNIST/raw



**Vectorization:**process of converting algorithms from operating on single values (scalar operations) to operating on vectors or matrices (vector operations). This process can significantly speed up computation .


Linear Regression Model
A linear regression model predicts the output variable
y as a linear combination of input variables
X, i.e.,
y=Xw+b, where
w is the weight vector and
b is the bias.

**Dataset,Weight,Bias:**
Dataset: A collection of data points used for training and evaluating models.

Weight: Parameters that the model learns during training, determining the
influence of input features on the output.

Bias: An additional parameter that allows the model to fit the data better by providing an offset.

Parameters: Values learned by the model during training (e.g., weights and biases).

Hyperparameters: Values set before the training process that control the learning process (e.g., learning rate, number of epochs).

**Generating Prediction Using Linear Regression Model**


In [6]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super(LinearRegressionModel,self).__init__()
    self.linear=nn.Linear(1,1) #1 input feature, 1 output

  def forward(self,x):
    return self.linear(x)#when the model is called, it applies the linear transformation to the input 'x'.

#Generating some data
x_train = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

model=LinearRegressionModel()
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

#Training the model
for epoch in range(100):
  model.train() #sets the model to training mode
  optimizer.zero_grad()
  outputs=model(x_train) #performs the forward pass to compute the model's prediction for 'x_train'
  loss=criterion(outputs,y_train)
  loss.backward() #backpropagates the loss,computing the gradient of the loss wrt model params
  optimizer.step()#Updates the model parameters using the computed gradients
  if(epoch+1)%10==0:
    print(f'Epoch [{epoch+1}/100], Loss:{loss.item():.4f}')

#Generating predictions
model.eval() #sets the model to evaluation mode, disabling
predicted=model(x_train).detach().numpy() #detach is used to detach the output from the computational graph
print(predicted)

Epoch [10/100], Loss:2.1024
Epoch [20/100], Loss:0.0661
Epoch [30/100], Loss:0.0127
Epoch [40/100], Loss:0.0107
Epoch [50/100], Loss:0.0100
Epoch [60/100], Loss:0.0095
Epoch [70/100], Loss:0.0089
Epoch [80/100], Loss:0.0084
Epoch [90/100], Loss:0.0079
Epoch [100/100], Loss:0.0074
[[2.1388113]
 [4.0672636]
 [5.9957156]
 [7.924168 ]]


**Loss Function Vs Cost Function**

Loss Function: Measures the difference between the predicted and actual values for a single data point.

Cost Function: Measures the average difference over the entire dataset.

**Mean Squared Error:**Is a common loss function for regression problems, calc as the average of the squared differences between the predicted and actual values.


In [7]:
def mean_squared_error(y_pred,y_true):
  return ((y_pred-y_true)**2).mean()

Forward vs. Backward Function

Forward Function: Computes the output of the model from the input.

Backward Function: Computes the gradient of the loss function with respect to the model parameters (backpropagation).

Gradient descent updates the weights and biases by moving them in the direction that reduces the loss function

**Epoch:**One complete pass through the entire training dataset

Increasing the no of epochs allows the model to learn better from the data, reducing the loss.

Learning Rate: hyperparameter that controls how much to change the model parameters in response to the estimated error

Learning rate: hyperparameter that controls how much to change the model params in response to estimated error each time the model weights are updated


**Optimizer in Pytorch**:Adjusts the weights and biases of the model to minimize the loss function(SGD,Adam,RMSprop)

In [8]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

**Machine Learning Part B**


Linear Regression
Purpose: Used for predicting continuous values.
Model:
y=Xw+b, where
y is the output,
X is the input features, w is the weights, and b is the bias.

Loss Function: Mean Squared Error (MSE).

Output: Continuous value.


Logistic Regression

Purpose: Used for binary classification problems.

Model: y=σ(Xw+b),
where
σ is the sigmoid function σ(z)= 1+e −z

1.
Loss Function: Binary Cross-Entropy.

Output: Probability (between 0 and 1).

**Importance of Batch size while training**:Refers to the number of training examples utilized in 1 iteration.

It affects the training speed,memory usage and gradient estimation(smaller batch sizes produce noisier gradient estimates which can help escape local minima)



**Cross Entropy:**Used in classification problems, measures the performance of a classification model whose output is prob bw 0 and 1. (Cross entropy loss is in -ve)

**Accuracy vs Loss Function:**

Accuracy: Measures the no of correct predictions. Metric to evaluate the model's performance.

Loss Function: Measures how well model is performing during training. Used to update the model's weights.

**Importance of Hidden Layer:Deep NN**

Hidden layer:Intermediate layers bw ip and op layers in a nn.They allow the network to learn complex patterns and reps

Deep NN:A network with multiple hidden layers. These networks can model complex relationships and achieve better performance on tasks like image recognition and NLP

**Train a Model with 1 Hidden Layer**

In [9]:
import torch
import torch.nn as nn
import numpy as np
#Generating synthetic data
np.random.seed(42)#seed for NumPy's random generator to ensure reproducibility
x_train=np.random.rand(100,1).astype(np.float32)#generates 100 random numbers b/w 0 and 1,reshaped into 100x1 array
y_train=3.5*x_train+np.random.randn(100,1).astype(np.float32)*0.5 #y=3.5x+noise term

x_train=torch.from_numpy(x_train)
y_train=torch.from_numpy(y_train)

#Defining the model with one hidden layer
class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN,self).__init__()
    self.hidden=nn.Linear(1,10)#Hidden layer with 10 neurons and 1 input feature
    self.relu=nn.ReLU()
    self.output=nn.Linear(10,1) #Output layer with 10 ip features and 1 output feature

  def forward(self,x): #passes input x into hidden layer, applies ReLU activation and passes result through output layer
    x=self.hidden(x)
    x=self.relu(x)
    x=self.output(x)
    return x

model=SimpleNN()
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

#Training the model
num_epochs=100
for epoch in range(num_epochs):
  model.train()
  optimizer.zero_grad() #clears the gradients of all optimized parameters
  outputs=model(x_train)
  loss=criterion(outputs,y_train)
  loss.backward() #Backpropagates the loss, computing the gradient of the loss wrt other params
  optimizer.step() #updates the model parameters using the computed gradients
  if(epoch+1)%10==0:
    print(f'Epoch[{epoch+1}/{num_epochs}],Loss:{loss.item():.4f}')

Epoch[10/100],Loss:1.5267
Epoch[20/100],Loss:0.9884
Epoch[30/100],Loss:0.8673
Epoch[40/100],Loss:0.8144
Epoch[50/100],Loss:0.7722
Epoch[60/100],Loss:0.7327
Epoch[70/100],Loss:0.6948
Epoch[80/100],Loss:0.6585
Epoch[90/100],Loss:0.6238
Epoch[100/100],Loss:0.5905


**Importance of GPU in training:**

Speed:GPUs can process multiple ops in parallel, significantly speeding up training.

Efficiency: GPUs are optimized for matrix and vector ops, mostly used in DL


**Device Parameter:**Specifies whether to run the model on a CPU or GPU.(Its easy to move tensors and models bw devices)

**Comparing training times on CPU and GPU**


In [10]:
import time
def train_model(device):
  model.to(device) #moves the model to the specific device
  x_train_device=x_train.to(device)
  y_train_device=y_train.to(device)#moves the training data to the specified device

  #Initializing optimizer and loss func
  optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
  criterion=nn.MSELoss()

  #Training loop with time measurement
  start_time=time.time()
  for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs=model(x_train_device)
    loss=criterion(outputs,y_train_device)
    loss.backward()
    optimizer.step()
  end_time=time.time()
  return end_time-start_time

In [15]:
#Training on CPU
cpu_time=train_model(torch.device('cpu'))
print(f'Training time on CPU:{cpu_time:.2f} seconds')

Training time on CPU:0.08 seconds


In [18]:
if torch.cuda.is_available():#Checks if GPU is available
    gpu_time=train_model(torch.device('cuda'))#CUDA(cpmplete unified device architecture) is an API by NVIDIA
    print(f"Training time on GPU:{gpu_time:.2f} seconds")
else:
  print("GPU is not available")
#For smaller models or datasets, the overhead of transferring data bw CPU and GPU can result in slower perf of GPU
#GPU Warm up time could also be a reason

Training time on GPU:0.09 seconds


**Machine Learning Part C**'

**Convolutional Neural Network**:is a DL algo used for analyzing visual data.They are designed to automatically and adaptively learn spatial hierarchies of features through back prop by using multiple building blocks such as convolution layers,pooling layers and fully connected layers

**Key Components:**

1. Convolution layer(nn.Conv2d)
2.Activation layer(nn.ReLU)
3.Pooling Layer(nn.MaxPool2d)
4.Sequential Model(nn.Sequential)

**Strides:**defines the step size with which the filter moves across the input image

eg) Input size:5x5, Filter size:3x3,Stride 2=> the filter skips every other pixel, generating a 2x2 output

**Padding:**involves adding extra pixels around the border of the input image.This can be useful for maintaining the spatial dimensions of op after convolution

eg) No padding=> reduces the output dimensions, a 5x5 input with 3x3 filter and no padding results in 3x3 output.

Zero Padding: Maintains the output dimensions. A 5x5 input with a 3x3 filter and padding of 1 results in 5x5 output.

Fully Connected Layers: in which each neuron is connected to every neuron in the previous layer. These are used at the end of a CNN to perform classification.

eg)ip from a con layer: a 1d vector of size 128(learned from the previous layer)

Fully Connected Layer: Connects this 128d input to a 10d output (for classification task with 10 classes)

In [2]:
#Simple CNN example
import torch
import torch.nn as nn
import torch.nn.functional as F

#padding=1 adds 1 pixel of zero-padding on each side of the input
class SimpleCNN(nn.Module):
  def __init__(self):
    super(SimpleCNN,self).__init__()#calls the constructor of the parent class nn.Module to initialize the base components
    self.conv1=nn.Conv2d(in_channels=1,out_channels=32,kernel_size=3,stride=1,padding=1)#kernel_size=> size of each filter
    self.pool=nn.MaxPool2d(kernel_size=2,stride=2,padding=0) #For downsampling the input along the spatial dimensions(width and height) but retains the most important features
    self.conv2=nn.Conv2d(in_channels=32,out_channels=64,kernel_size=3,stride=1,padding=1)
    self.fc1=nn.Linear(64*7*7,128)#computed based on the output size of the last pooling layer,64*7*7=>no of input features,128=>no of output features
    self.fc2=nn.Linear(128,10)

  def forward(self,x):
    x=self.pool(F.relu(self.conv1(x)))#applies 1st conv layer, followed by a ReLU activation function,then a maxpooling operation
    x=self.pool(F.relu(self.conv2(x)))
    x=x.view(-1,64*7*7)#flattens the output from conv layers to a vector of size 64*7*7 to feed into the fully connected layer. -1=>auto infer the batch size
    x=F.relu(self.fc1(x))#Applies 1st FCL followed by a relu
    x=self.fc2(x)#applies 2nd fcl to get the final output
    return x
model=SimpleCNN()
print(model)#prints the model arch, showing the layers and their configs


SimpleCNN(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (fc1): Linear(in_features=3136, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


**Overfitting:**occurs when a model performs well on the training data but poorly on unseen test data. It means the model has learned the training data too well, including its noise and outliers.

**Strategies to avoid overfitting:**

1.Learning rate schedular=>to improve convergence and avoid overfitting

2.Weight decay=>adding a regularization term to the loss function to penalize large weights

3.Gradient clipping=> Clipping the gradients during back prop to prevent exploding gradient problem which may destabilize the training process

In [4]:
#scheduler=torch.optim.lr_scheduler.StepLR(optimizer,step_size=30,gamma=0.1)
#optimizer=torch.optim.SGD(model.parameters(),lr=0.01,weight_decay=0.001)
#torch.nn.utils.clip_grad_norm_(model.parameters(),max_norm=2.0)

**Regulaalrization of Data**

**Data Normalization:**involves scaling the input data to a standard range (e.g., 0 to 1 or -1 to 1). It helps improve the convergence rate of the gradient descent algorithm.


In [5]:
from torchvision import transforms
transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,),(0.5,))#specifies mean and sd
])

**Data Augmentation:**artificially increases the size of the training dataset by creating modified versions of images in the dataset. This helps improve the model's generalization.

In [6]:
transform=transforms.Compose([
    transforms.RandomHorizontalFlip(),#flip image horizontally with prob of 0.5
    transforms.RandomRotation(10),#randomly rotates input image from -10 to 10 degrees
    transforms.ToTensor()
])

**Signal Processing Techniques: ** involve analyzing, modifying and synthesizing signals.(Fourier transform,filtering, time-domain analysis) for audio processing, communications and image processing.

**ONNX:** (Open neural network exchange) is an open source format for representing ML Models. Allows models trained in different frameworks to be transferred bw them, improving deployement flexibility.